-- =============================================================
-- Supabase Hearth-Pulse Setup
-- Run this SQL in your Supabase project SQL Editor:
--   Supabase Dashboard → SQL Editor → New query → paste → Run
--
-- Based on: https://github.com/bennytaccardi/supabase-hearth-pulse
--
-- This creates a lightweight "ping table". The hearth-pulse heartbeat
-- runs every 30 seconds client-side:
--   1. DELETE all rows from hearth_pulse   (keeps DB active)
--   2. INSERT a fresh row with a UUID name (proves write works)
-- =============================================================

CREATE TABLE IF NOT EXISTS "hearth_pulse" (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name   TEXT   NULL DEFAULT ''::TEXT,
    random UUID   NULL DEFAULT gen_random_uuid(),
    CONSTRAINT "hearth_pulse_pkey" PRIMARY KEY (id)
);

-- Enable RLS and allow anon/authenticated to operate on this table
ALTER TABLE "hearth_pulse" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow hearth_pulse operations"
  ON "hearth_pulse"
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Seed one row so the first DELETE doesn't fail on an empty table
INSERT INTO "hearth_pulse" (name)
VALUES ('init')
ON CONFLICT DO NOTHING;
